name: RadioBoard
main: io.github.bananapuncher714.radioboard.RadioBoard
version: 0.1
author: BananaPuncher714
authors:
- "jetp250"
softdepend:
- "Multiverse-Core"
- "PlaceholderAPI"
description: Displays images
commands:
    video:
        aliases: []