name: RadioBoard
main: io.github.bananapuncher714.radioboard.RadioBoard
version: 1.2
author: BananaPuncher714
authors:
- "jetp250"
softdepend:
- "Multiverse-Core"
- "PlaceholderAPI"
description: The ultimate universal map display plugin
permissions:
    radioboard.admin:
        default: op
commands:
    radioboard:
        aliases: []