name: RadioBoard
main: io.github.bananapuncher714.radioboard.RadioBoard
version: 1.0
author: BananaPuncher714
authors:
- "jetp250"
softdepend:
- "Multiverse-Core"
- "PlaceholderAPI"
description: The ultimate universal map display plugin
commands:
    radioboard:
        aliases: []